-- GENERATED FILE — do not edit by hand.
-- Source: data/products.csv
-- Regenerate with:  python tools/generate-seed.py   (119 products)
--
-- Idempotent: safe to run on every boot.
-- Table names are capitalised and singular — always double-quote them.

-- 1. Categories first: products reference them by id.
INSERT INTO "Category" (name) VALUES
  ('Cooking Oils & Ghee'),
  ('Masalas & Spices'),
  ('Soaps & Body Wash'),
  ('Tea & Coffee'),
  ('Toothpastes & Oral Care')
ON CONFLICT (name) DO NOTHING;

-- 2. Products. Category resolved by name, never by hardcoded id.
INSERT INTO "Product" (item_id, name, weight, price, category_id, image_url) VALUES
  ('ITEM-001', 'Sufi Canola Oil Pouch', '1 Litre', 598.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-001.jpg'),
  ('ITEM-002', 'Sufi Canola Oil Bottle', '3 Litre', 1845.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-002.jpg'),
  ('ITEM-003', 'Sufi Canola Oil Bottle (4.5 Ltr)', '4.5 Litre', 2740.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-003.jpg'),
  ('ITEM-004', 'Sufi Soyabean Oil Pouch ( 1 Ltr )', '1 Litre', 620.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-004.jpg'),
  ('ITEM-005', 'Sufi Banaspati Tin', '5 Kg', 3080.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-005.jpg'),
  ('ITEM-006', 'Sufi Sunflower Oil Pouch (1Ltr)', '1 Litre', 610.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-006.jpg'),
  ('ITEM-007', 'Sufi Sunflower Oil Bottle (4.5 Ltr)', '4.5 Litre', 2835.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-007.jpg'),
  ('ITEM-008', 'Sufi Sunflower Oil Bottle ( 3Ltr)', '3 Litre', 1905.00,
    (SELECT id FROM "Category" WHERE name = 'Cooking Oils & Ghee'),
    '/images/ITEM-008.jpg'),
  ('ITEM-009', 'Colgate MaxFresh Spicy Fresh Toothpaste 125g', '125 g', 325.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-009.jpg'),
  ('ITEM-010', 'Colgate MaxFresh Citrus Blast Toothpaste 125g', '125 g', 325.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-010.jpg'),
  ('ITEM-011', 'Colgate Zig Zag Toothbrush - Soft', '1 unit', 146.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-011.jpg'),
  ('ITEM-012', 'Colgate Maximum Cavity Toothpaste-Brush pack', '75 g', 220.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-012.jpg'),
  ('ITEM-013', 'Colgate Slimsoft Charcoal Toothbrush', '1 unit', 285.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-013.jpg'),
  ('ITEM-014', 'Colgate Maximum Cavity Protection Toothpaste  Regular Buy 1 Get 1 Free', '200 g', 437.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-014.jpg'),
  ('ITEM-015', 'Colgate Plax Peppermint Anti Germs Mouth Wash', '250 ml', 540.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-015.jpg'),
  ('ITEM-016', 'Colgate Sensitive Pro-Relief Original Toothpaste 100g', '100 g', 490.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-016.jpg'),
  ('ITEM-017', 'Colgate Plax Fresh Mint Mouthwash', '500 ml', 1045.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-017.jpg'),
  ('ITEM-018', 'Colgate Herbal Toothpaste 100g', '100 g', 220.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-018.png'),
  ('ITEM-019', 'Colgate MaxFresh Peppermint Ice Toothpaste 125g', '125 g', 325.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-019.jpg'),
  ('ITEM-020', 'Colgate MaxFresh Peppermint Ice Toothpaste 75g', '75 g', 220.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-020.jpg'),
  ('ITEM-021', 'Colgate Extra Clean Toothbrush - Medium', '1 unit', 104.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-021.jpg'),
  ('ITEM-022', 'Colgate Twister Toothbrush - Soft', '1 unit', 140.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-022.jpg'),
  ('ITEM-023', 'Colgate Max Fresh Green Tooth Paste', '75 g', 220.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-023.png'),
  ('ITEM-024', 'Colgate MaxFresh Spicy Fresh Toothpaste', '75 g', 220.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-024.jpg'),
  ('ITEM-025', 'Colgate Herbal Toothpaste 150g', '150 g', 325.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-025.jpg'),
  ('ITEM-026', 'Colgate 360 Base Toothbrush - Soft', '1 unit', 210.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-026.jpg'),
  ('ITEM-027', 'Colgate Navigator Plus Toothbrush', '1 unit', 210.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-027.jpg'),
  ('ITEM-028', 'Colgate Slimsoft Regular Toothbrush', '1 unit', 200.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-028.jpg'),
  ('ITEM-029', 'Colgate 360 Sensitive Pro-Relief Toothbrush', '1 unit', 240.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-029.jpg'),
  ('ITEM-030', 'Colgate Classic Deep Clean Tooth Brush- Medium', '1 unit', 80.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-030.jpg'),
  ('ITEM-031', 'Colgate Total Advanced Health Toothpaste', '100 g', 349.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-031.jpg'),
  ('ITEM-032', 'Colgate Premier Clean Soft Medium Brush Buy 2 Get 1 Free', '1 unit', 180.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-032.jpg'),
  ('ITEM-033', 'Colgate Total Advance Tooth Paste', '150 g', 490.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-033.jpg'),
  ('ITEM-034', 'Colgate Max Fresh Toothpaste125gm', '125 g', 325.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-034.jpg'),
  ('ITEM-035', 'Colgate Maximum Cavity Protection Toothpaste', '300 g', 655.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-035.jpg'),
  ('ITEM-036', 'Colgate Extra Clean Medium Tooth Brush Medium', '1 unit', 200.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-036.jpg'),
  ('ITEM-037', 'Colgate Plax Freshmint Splash Mouth Wash', '250 ml', 500.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-037.jpg'),
  ('ITEM-038', 'Colgate Plax Peppermint Fresh Mouthwash', '500 ml', 1045.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-038.jpg'),
  ('ITEM-039', 'Colgate Fluoride Toothpaste Cool Stripe 100 ml', '100 ml', 950.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-039.jpg'),
  ('ITEM-040', 'Close Up Toothpaste FIFA Gold (85gm)', '85 g', 450.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-040.png'),
  ('ITEM-041', 'Oral-B PRO-FLEX LUXE', '1 unit', 565.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-041.jpg'),
  ('ITEM-042', 'Oral-B 3D White Toothbrush', '1 unit', 560.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-042.jpg'),
  ('ITEM-043', 'Oral-B Gentle Care Toothbrush', '1 unit', 560.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-043.png'),
  ('ITEM-044', 'Oral-B Pro Expert Toothbrush', '1 unit', 560.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-044.jpg'),
  ('ITEM-045', 'Colgate Sensitive Pro-Relief Expert (With Free Slim Soft Brush)', '100 g', 440.00,
    (SELECT id FROM "Category" WHERE name = 'Toothpastes & Oral Care'),
    '/images/ITEM-045.jpg'),
  ('ITEM-046', 'Lipton Yellow Label Tea - 900g - Save Rs. 200', '900 g', 1999.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-046.jpg'),
  ('ITEM-047', 'Lipton Danedar Tea - 900g', '900 g', 1800.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-047.jpg'),
  ('ITEM-048', 'Lipton Earl Grey (25 Tea Bags)', '1 unit', 500.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-048.jpg'),
  ('ITEM-049', 'Lipton Lemon & Ginger (20 Tea bags)', '1 unit', 900.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-049.jpg'),
  ('ITEM-050', 'Lipton Chamomile (20 Tea Bags)', '1 unit', 900.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-050.jpg'),
  ('ITEM-051', 'Lipton Mint (20 Tea Bags)', '1 unit', 900.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-051.jpg'),
  ('ITEM-052', 'Lipton Yellow Label (430 gm)', '430 g', 1100.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-052.png'),
  ('ITEM-053', 'Lipton Danedar 170G - Black Tea', '170 g', 400.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-053.jpg'),
  ('ITEM-054', 'Lipton Yellow Label Tea - 85g - Save Rs. 20', '85 g', 200.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-054.jpg'),
  ('ITEM-055', 'Lipton Green Tea Mixed Berries (25 Tea Bags)', '1 unit', 300.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-055.jpg'),
  ('ITEM-056', 'Lipton Danedar Tea - 430g', '430 g', 1049.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-056.jpg'),
  ('ITEM-057', 'Lipton English Breakfast (25 Tea Bags)', '1 unit', 500.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-057.jpg'),
  ('ITEM-058', 'Lipton Hibiscus (20 Tea Bags)', '1 unit', 900.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-058.jpg'),
  ('ITEM-059', 'Tapal Danedar Tea 900 gm', '900 g', 1850.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-059.jpg'),
  ('ITEM-060', 'Tapal Danedar Tea', '170 g', 390.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-060.jpg'),
  ('ITEM-061', 'Tapal Family Mixture Tea', '430 g', 950.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-061.jpg'),
  ('ITEM-062', 'Tapal Lemon Green Tea Bags 90', '1 unit', 720.00,
    (SELECT id FROM "Category" WHERE name = 'Tea & Coffee'),
    '/images/ITEM-062.jpg'),
  ('ITEM-063', 'LUX Soap Nourished Glow LOTUS Vitamin C + Floral Oil 98 gm', '98 g', 190.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-063.jpg'),
  ('ITEM-064', 'Lux Soap Pink Vitamin C Glycerine', '128 g', 160.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-064.png'),
  ('ITEM-065', 'Palmolive Naturals Refreshing Glow 3in1 98gm*3', '98 g', 364.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-065.jpg'),
  ('ITEM-066', 'Palmolive Naturals Hydrating Glow Bar Soap', '98 g', 128.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-066.jpg'),
  ('ITEM-067', 'Palmolive Naturals Radiant Glow Bar Soap', '98 g', 118.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-067.webp'),
  ('ITEM-068', 'Palmolive Naturals Radiant Glow Bar Soap', '165 g', 165.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-068.jpg'),
  ('ITEM-069', 'Palmolive Radiant Glow Soap 3in1 Save Rs.25', '130 g', 425.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-069.jpg'),
  ('ITEM-070', 'LUX Body Wash Fresh Aloe Vera & Freesia Scent 250ml', '250 ml', 450.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-070.jpg'),
  ('ITEM-071', 'Lux Renewed Glow Body Wash', '450 ml', 950.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-071.jpg'),
  ('ITEM-072', 'Lux Clear Glow Body Wash', '450 ml', 950.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-072.jpg'),
  ('ITEM-073', 'Lux Bouncy Glow Body Wash', '450 ml', 950.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-073.jpg'),
  ('ITEM-074', 'Dettol Cooling Sensation Soap Pack Of 3 Save Rs. 25', '1 unit', 425.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-074.jpg'),
  ('ITEM-075', 'Lux Pink Rose Glow Soap', '167 g', 180.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-075.jpg'),
  ('ITEM-076', 'Lux Pink Rose Glow Soap', '50 g', 60.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-076.jpg'),
  ('ITEM-077', 'Dettol Soap Fresh Lemon Anti bacterial', '95 g', 130.00,
    (SELECT id FROM "Category" WHERE name = 'Soaps & Body Wash'),
    '/images/ITEM-077.jpg'),
  ('ITEM-078', 'National Chat Masala', '50 g', 120.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-078.jpg'),
  ('ITEM-079', 'National Chicken Tikka Masala Mix', '45 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-079.jpg'),
  ('ITEM-080', 'National Quorma Masala Mix Double Pack', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-080.jpg'),
  ('ITEM-081', 'National Chicken Tikka Masala Recipe Mix Double Pack', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-081.jpg'),
  ('ITEM-082', 'National Pulao Masala Recipe Mix', '50 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-082.jpg'),
  ('ITEM-083', 'National Achar Gosht Masala Recipe Mix', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-083.jpg'),
  ('ITEM-084', 'National Karachi khas Nihari Masala Recipe Mix', '60 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-084.jpg'),
  ('ITEM-085', 'National Shami Kabab Masala Mix', '45 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-085.png'),
  ('ITEM-086', 'National Haleem Masala Mix', '48 g', 149.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-086.png'),
  ('ITEM-087', 'National Fish Masala Recipe Mix', '50 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-087.png'),
  ('ITEM-088', 'National Murghi   نیشنل مرغ مصالحہ', '50 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-088.png'),
  ('ITEM-089', 'National Paaya   نیشنل پايا مصالحہ', '39 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-089.png'),
  ('ITEM-090', 'National Fish Masala Mix', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-090.jpg'),
  ('ITEM-091', 'National Biryani Masala Mix', '45 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-091.jpg'),
  ('ITEM-092', 'National Chat Masala', '100 g', 190.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-092.jpg'),
  ('ITEM-093', 'National Quorma Masala Mix', '50 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-093.jpg'),
  ('ITEM-094', 'National Karahi Gosht Masala Mix', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-094.png'),
  ('ITEM-095', 'National Sindhi Biryani Masala Mix', '46 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-095.jpg'),
  ('ITEM-096', 'National Karachi Khaas Bombay Biryani', '70.04 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-096.jpg'),
  ('ITEM-097', 'National Karachi Khaas Bombay Biryani Masala', '140 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-097.jpg'),
  ('ITEM-098', 'National Chapli Kabab Masala Mix', '72 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-098.png'),
  ('ITEM-099', 'National Seekh Kabab Masala Recipe Mix', '50 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-099.png'),
  ('ITEM-100', 'National Pulao Masala', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-100.png'),
  ('ITEM-101', 'National Quick Cook Haleem Masala Mix', '300 g', 314.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-101.png'),
  ('ITEM-102', 'National Murghi Masala Mix Double Pack', '100 g', 290.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-102.jpg'),
  ('ITEM-103', 'National Daighi Danedar Haleem', '300 g', 350.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-103.jpg'),
  ('ITEM-104', 'National Karachi Khaas Nihari Double Pack', '110 g', 275.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-104.jpg'),
  ('ITEM-105', 'National Red Chilli Powder', '100 g', 200.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-105.jpg'),
  ('ITEM-106', 'National Turmeric Powder', '50 g', 140.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-106.jpg'),
  ('ITEM-107', 'National Kali Mirch Powder', '25 g', 165.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-107.jpg'),
  ('ITEM-108', 'National Red Chilli Powder', '200 g', 380.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-108.png'),
  ('ITEM-109', 'National Coriander Powder', '200 g', 350.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-109.jpg'),
  ('ITEM-110', 'National Red Chilli Powder', '50 g', 110.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-110.png'),
  ('ITEM-111', 'National Ginger Powder', '50 g', 250.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-111.jpg'),
  ('ITEM-112', 'National Red Chilli Powder', '400 g', 730.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-112.png'),
  ('ITEM-113', 'National Black Pepper Powder', '50 g', 310.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-113.jpg'),
  ('ITEM-114', 'National Garam Masala Powder', '50 g', 330.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-114.jpg'),
  ('ITEM-115', 'National Turmeric Powder', '100 g', 270.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-115.jpg'),
  ('ITEM-116', 'National Garam Masala Powder', '25 g', 165.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-116.jpg'),
  ('ITEM-117', 'National Garlic Powder', '50 g', 150.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-117.jpg'),
  ('ITEM-118', 'National Cumin Seeds', '50 g', 350.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-118.jpg'),
  ('ITEM-119', 'National Kasuri Methi   نیشنل قصوری میتھی', '25 g', 80.00,
    (SELECT id FROM "Category" WHERE name = 'Masalas & Spices'),
    '/images/ITEM-119.jpg')
ON CONFLICT (item_id) DO NOTHING;
